[tool.poetry]
name = "textual-tutorial"
version = "0.1.0"
description = ""
authors = ["KennyVaneetvelde <kenny@inosta.be>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
textual = "^0.85.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
